#!/bin/bash

# Get the current branch name
current_branch=$(git branch --show-current)
echo "Running command:"
echo "git reset --hard origin/$current_branch"
git reset --hard "origin/$current_branch"
